select * from customerbeh

##Q1 What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount)as Total_revenue 
from customerbeh
group by gender;


##Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount 
from customerbeh
where discount_applied='Yes' and purchase_amount >=(select avg(purchase_amount) from customerbeh)


##Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) as average_rating from customerbeh
group by item_purchased
order by avg(review_rating)desc
limit 5


##Q4. Compare the average Purchase Amounts between Standard and Express Shipping?

select shipping_type,avg(purchase_amount)
from customerbeh
where shipping_type in ('standard','Express')
group by shipping_type
order by avg(purchase_amount) 


##Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?

select subscription_status,round(avg(purchase_amount),2),sum(purchase_amount) from customerbeh
group by subscription_status



##Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100*sum(Case when discount_applied ='Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customerbeh
group by item_purchased
order by discount_rate desc
limit 5


##Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?


with customer_type as(
select previous_purchases,customer_id,
case when previous_purchases = 1 then 'New' 
      when previous_purchases <= 10 then 'Recurring'
      else 'Loyal' end as customer_segment
from customerbeh)
select customer_segment,count(*) as'Number_of_customer'
from customer_type
group by customer_segment


##Q8. What are the top 3 most purchased products within each category?


with item_count as (
select category,item_purchased, count(*) as total,
row_number() over(partition by category order by count(*) desc ) as item_rank
from customerbeh
group by category,item_purchased)
select item_rank,category,item_purchased,total
from item_count
where item_rank <=3


##Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(*)
from customerbeh
where previous_purchases>5
group by subscription_status


##Q10. What is the revenue contribution of each age group?

select age_group,sum(purchase_amount) as revenue,count(*)
from customerbeh
group by age_group
order by revenue desc






































